import { Router } from "express";

const router = Router();

const ROBOT_PARTS = [
  // ── CHASSIS (12) ──────────────────────────────────────────────────────────
  {
    id: "body-titan",
    name: "TITAN",
    category: "body",
    stats: { armor: 90, power: 60, speed: 30, energy: 70 },
    color: "#8B7355",
    description: "A massive armored chassis built for endurance. Slow but nearly indestructible.",
    specialAbility: "Iron Fortress",
  },
  {
    id: "body-wasp",
    name: "WASP",
    category: "body",
    stats: { armor: 30, power: 50, speed: 95, energy: 80 },
    color: "#FFD700",
    description: "An agile lightweight frame engineered for speed and evasion.",
    specialAbility: "Afterburner",
  },
  {
    id: "body-goliath",
    name: "GOLIATH",
    category: "body",
    stats: { armor: 75, power: 80, speed: 40, energy: 60 },
    color: "#FF6B2B",
    description: "Balanced war machine. Heavy power in a durable industrial frame.",
    specialAbility: "Overcharge",
  },
  {
    id: "body-phantom",
    name: "PHANTOM",
    category: "body",
    stats: { armor: 45, power: 70, speed: 75, energy: 65 },
    color: "#4B0082",
    description: "Ghost-class stealth chassis. Built for unpredictable movement and ambush.",
    specialAbility: "Phase Shift",
  },
  {
    id: "body-fortress",
    name: "FORTRESS",
    category: "body",
    stats: { armor: 100, power: 40, speed: 20, energy: 50 },
    color: "#708090",
    description: "Maximum protection shell. Built like a bunker — moves like one too.",
    specialAbility: "Siege Mode",
  },
  {
    id: "body-viper",
    name: "VIPER",
    category: "body",
    stats: { armor: 40, power: 65, speed: 90, energy: 70 },
    color: "#39FF14",
    description: "Strike fast, strike first. Precision attack frame for hit-and-run tactics.",
    specialAbility: "Venom Strike",
  },
  {
    id: "body-colossus",
    name: "COLOSSUS",
    category: "body",
    stats: { armor: 85, power: 75, speed: 25, energy: 55 },
    color: "#5C5C5C",
    description: "Oversized combat frame. Dominates by pure mass and raw force.",
    specialAbility: "Seismic Slam",
  },
  {
    id: "body-wraith",
    name: "WRAITH",
    category: "body",
    stats: { armor: 35, power: 80, speed: 85, energy: 60 },
    color: "#1E90FF",
    description: "High-speed attack ghost. Trades armor for terrifying offensive potential.",
    specialAbility: "Spectral Rush",
  },
  {
    id: "body-bulwark",
    name: "BULWARK",
    category: "body",
    stats: { armor: 95, power: 45, speed: 15, energy: 45 },
    color: "#B22222",
    description: "Defensive fortress chassis. Designed to absorb punishment indefinitely.",
    specialAbility: "Last Stand",
  },
  {
    id: "body-lynx",
    name: "LYNX",
    category: "body",
    stats: { armor: 50, power: 55, speed: 88, energy: 75 },
    color: "#C8A050",
    description: "Agile mid-weight predator. Balances speed with enough bite to finish fights.",
    specialAbility: "Pounce",
  },
  {
    id: "body-rhino",
    name: "RHINO",
    category: "body",
    stats: { armor: 80, power: 85, speed: 35, energy: 50 },
    color: "#888888",
    description: "Charging brute force chassis. Built to ram and destroy on impact.",
    specialAbility: "Gore Charge",
  },
  {
    id: "body-shadow",
    name: "SHADOW",
    category: "body",
    stats: { armor: 25, power: 60, speed: 100, energy: 90 },
    color: "#1A1A2E",
    description: "Ultra-light stealth sprinter. Fastest chassis — almost zero protection.",
    specialAbility: "Ghost Step",
  },

  // ── WEAPONS (12) ──────────────────────────────────────────────────────────
  {
    id: "attack-titan-disc",
    name: "TITAN DISC",
    category: "attack",
    stats: { armor: 40, power: 95, speed: 25, energy: 30 },
    color: "#C0C0C0",
    description: "Full-body spinning steel disc. Shreds anything it contacts on all sides.",
    specialAbility: "Full Spin Shred",
  },
  {
    id: "attack-hammerhead",
    name: "HAMMERHEAD",
    category: "attack",
    stats: { armor: 50, power: 85, speed: 35, energy: 38 },
    color: "#A0522D",
    description: "Hydraulic overhead hammer. Single devastating downward strike.",
    specialAbility: "Piston Crush",
  },
  {
    id: "attack-vertical-spinner",
    name: "VERTICAL SPINNER",
    category: "attack",
    stats: { armor: 45, power: 90, speed: 30, energy: 32 },
    color: "#FF4500",
    description: "Vertical blade disc that launches opponents airborne on contact.",
    specialAbility: "Launch Uppercut",
  },
  {
    id: "attack-lifter-fork",
    name: "LIFTER FORK",
    category: "attack",
    stats: { armor: 50, power: 55, speed: 45, energy: 45 },
    color: "#B8C8D8",
    description: "Low hydraulic fork that flips enemies upside down.",
    specialAbility: "Flip Over",
  },
  {
    id: "attack-flail-chain",
    name: "FLAIL CHAIN",
    category: "attack",
    stats: { armor: 50, power: 75, speed: 40, energy: 40 },
    color: "#3C3C3C",
    description: "Whipping steel chain with a spiked ball. Unpredictable and terrifying.",
    specialAbility: "Chain Lash",
  },
  {
    id: "attack-crusher-claw",
    name: "CRUSHER CLAW",
    category: "attack",
    stats: { armor: 50, power: 80, speed: 35, energy: 38 },
    color: "#DC143C",
    description: "Hydraulic claw that grabs and crushes opponents from above.",
    specialAbility: "Death Grip",
  },
  {
    id: "attack-horizontal-spinner",
    name: "HORIZONTAL SPINNER",
    category: "attack",
    stats: { armor: 42, power: 88, speed: 32, energy: 32 },
    color: "#FF8C00",
    description: "Low-riding horizontal blade bar. Shreds wheels and bottom armor.",
    specialAbility: "Floor Shredder",
  },
  {
    id: "attack-spike-ramrod",
    name: "SPIKE RAMROD",
    category: "attack",
    stats: { armor: 50, power: 65, speed: 50, energy: 50 },
    color: "#8B4513",
    description: "Fixed forward spike for pure charge attacks. Simple and brutal.",
    specialAbility: "Impale",
  },
  {
    id: "attack-pneumatic-lance",
    name: "PNEUMATIC LANCE",
    category: "attack",
    stats: { armor: 50, power: 78, speed: 42, energy: 40 },
    color: "#87CEEB",
    description: "Compressed air spike that fires on contact. Punches through armor.",
    specialAbility: "Armor Pierce",
  },
  {
    id: "attack-drum-spinner",
    name: "DRUM SPINNER",
    category: "attack",
    stats: { armor: 45, power: 82, speed: 38, energy: 34 },
    color: "#808080",
    description: "Rotating drum that chews into opponents continuously on contact.",
    specialAbility: "Continuous Grind",
  },
  {
    id: "attack-wedge-slicer",
    name: "WEDGE SLICER",
    category: "attack",
    stats: { armor: 50, power: 50, speed: 50, energy: 50 },
    color: "#E8E8E8",
    description: "Razor-edged wedge that slides under opponents and tips them.",
    specialAbility: "Undercut",
  },
  {
    id: "attack-plasma-torch",
    name: "PLASMA TORCH",
    category: "attack",
    stats: { armor: 50, power: 70, speed: 45, energy: 28 },
    color: "#00CED1",
    description: "Cutting torch that burns through armor over sustained contact.",
    specialAbility: "Melt Through",
  },

  // ── DEFENSE (12) ──────────────────────────────────────────────────────────
  {
    id: "defense-titanium-shell",
    name: "TITANIUM SHELL",
    category: "defense",
    stats: { armor: 90, power: 50, speed: 30, energy: 35 },
    color: "#C0C0C0",
    description: "Full-body titanium wrap. Extremely tough, adds significant weight.",
    specialAbility: "Titan Skin",
  },
  {
    id: "defense-reactive-panels",
    name: "REACTIVE PANELS",
    category: "defense",
    stats: { armor: 85, power: 50, speed: 40, energy: 30 },
    color: "#8B0000",
    description: "Explosive-reactive plates detonate on impact to absorb hits.",
    specialAbility: "Counterburst",
  },
  {
    id: "defense-carbon-weave",
    name: "CARBON WEAVE",
    category: "defense",
    stats: { armor: 65, power: 50, speed: 48, energy: 45 },
    color: "#2F4F4F",
    description: "Lightweight carbon fiber mesh. Minimal protection, maximum agility.",
    specialAbility: "Light Frame",
  },
  {
    id: "defense-ceramic-composite",
    name: "CERAMIC COMPOSITE",
    category: "defense",
    stats: { armor: 80, power: 50, speed: 38, energy: 40 },
    color: "#F5F5DC",
    description: "Heat-resistant ceramic tiles. Absorbs energy weapons and fire.",
    specialAbility: "Heat Shield",
  },
  {
    id: "defense-steel-fortress-wrap",
    name: "STEEL FORTRESS WRAP",
    category: "defense",
    stats: { armor: 95, power: 45, speed: 22, energy: 30 },
    color: "#696969",
    description: "Thick rolled steel plating welded on all sides. Brute protection.",
    specialAbility: "Welded Wall",
  },
  {
    id: "defense-ablative-foam",
    name: "ABLATIVE FOAM COAT",
    category: "defense",
    stats: { armor: 70, power: 50, speed: 45, energy: 45 },
    color: "#A9A9A9",
    description: "Energy-absorbing foam. Cheap but effective against spinners.",
    specialAbility: "Spinner Soak",
  },
  {
    id: "defense-polycarbonate-shield",
    name: "POLYCARBONATE SHIELD",
    category: "defense",
    stats: { armor: 75, power: 50, speed: 42, energy: 42 },
    color: "#87CEEB",
    description: "Transparent impact shield at front. See the opponent through it.",
    specialAbility: "Front Guard",
  },
  {
    id: "defense-self-healing-polymer",
    name: "SELF-HEALING POLYMER",
    category: "defense",
    stats: { armor: 72, power: 50, speed: 44, energy: 25 },
    color: "#00FA9A",
    description: "Smart material that slowly repairs fractures during combat.",
    specialAbility: "Auto-Repair",
  },
  {
    id: "defense-chain-mail-skirt",
    name: "CHAIN MAIL SKIRT",
    category: "defense",
    stats: { armor: 68, power: 50, speed: 40, energy: 47 },
    color: "#9E9E9E",
    description: "Steel chain curtain protecting wheels and underside.",
    specialAbility: "Underbelly Guard",
  },
  {
    id: "defense-deflector-wedge",
    name: "DEFLECTOR WEDGE ARMOR",
    category: "defense",
    stats: { armor: 78, power: 50, speed: 42, energy: 45 },
    color: "#E8E8E8",
    description: "Angled front armor designed to deflect attacks upward.",
    specialAbility: "Spinner Deflect",
  },
  {
    id: "defense-nano-ceramic",
    name: "NANO-CERAMIC COAT",
    category: "defense",
    stats: { armor: 62, power: 50, speed: 50, energy: 42 },
    color: "#7B68EE",
    description: "Microscopic ceramic layer. Almost invisible but surprisingly resilient.",
    specialAbility: "Iridescent Guard",
  },
  {
    id: "defense-iron-fortress",
    name: "IRON FORTRESS SHELL",
    category: "defense",
    stats: { armor: 100, power: 40, speed: 15, energy: 25 },
    color: "#4A4A4A",
    description: "Triple-layered iron plating. Heaviest defense available. A walking tank.",
    specialAbility: "Impenetrable",
  },
];

router.get("/parts", (req, res) => {
  res.json(ROBOT_PARTS);
});

export default router;
